version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq_DeliGo
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      - DeliGo_network

  postgres:
    image: postgres:17-alpine
    container_name: postgres_DeliGo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: delivery
      POSTGRES_USER: delivery
      POSTGRES_DB: delivery
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - delivery_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - delivery_network

networks:
  delivery_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
